#!/usr/bin/env bash

set -e

docker rm --force --volumes recluse-test-postgres || true
docker pull postgres:alpine

docker run --detach --name recluse-test-postgres \
  --publish 5432 \
  --env POSTGRES_PASSWORD= \
  postgres:alpine
