#!/usr/bin/env bash

PUBLISHED="$(docker port recluse-postgres-test 5432)"

echo "export PGHOST=localhost"
echo "export PGPORT=${PUBLISHED#"0.0.0.0:"}"
echo "export PGUSER=postgres"
echo "export PGPASSWORD=recluse"
